#!/bin/bash
set -e

echo "=== SAFE: Enable root SSH login with KEY only ==="

PUBKEY='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqYatmrBBuQLQkleRtZDGi7ECc34LcLYK2AavX9tohmuILqIYYRRSrc5StqzSWkFe3S9Ke99lbqKu7a0GLsxsJe5rbsgxiZ8TLGoKmQhNlw3HxkbAif0R3t+dmfLn8ch2zhz14BJmb/YMmxH8LTTwW9MXz+YniPBXmG0IA0bT6Zrex2Bq9hx9vYytMuye+QIEx2SITKOU9r2QxUQ+CfLIimCNzsmXSwj3N7vEI3f9+StKaG//ZM0NAXL65dRQCkUrL+Z9AX8C2JlpLpVLgFcFDGkeckZ7FpceDrazoyu/UnHUKlvrWqAySh/gFZVmneIrQBQL2oAO0ZmrIuGHPfBOd Generated by ArvanCloud'

### 1) Prepare .ssh
mkdir -p /root/.ssh
chmod 700 /root/.ssh

if ! grep -q "$PUBKEY" /root/.ssh/authorized_keys 2>/dev/null; then
  echo "$PUBKEY" >> /root/.ssh/authorized_keys
fi

chmod 600 /root/.ssh/authorized_keys
chown -R root:root /root/.ssh

echo "[OK] SSH key installed for root"

### 2) Backup sshd_config
BACKUP="/etc/ssh/sshd_config.bak.$(date +%F_%H-%M-%S)"
cp /etc/ssh/sshd_config "$BACKUP"
echo "[OK] Backup created: $BACKUP"

### 3) Secure SSH configuration
sed -i 's/^#\?PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config
sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
sed -i 's/^#\?ChallengeResponseAuthentication.*/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config
sed -i 's/^#\?KbdInteractiveAuthentication.*/KbdInteractiveAuthentication no/' /etc/ssh/sshd_config
sed -i 's/^#\?UsePAM.*/UsePAM no/' /etc/ssh/sshd_config
sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config

echo "[OK] sshd_config updated (key-only root login)"

### 4) Validate config BEFORE restart
if sshd -t; then
  echo "[OK] sshd config test passed"
else
  echo "[ERROR] sshd config invalid! Rolling back..."
  cp "$BACKUP" /etc/ssh/sshd_config
  exit 1
fi

### 5) Restart safely
systemctl reload ssh 2>/dev/null || systemctl reload sshd 2>/dev/null || systemctl restart ssh || systemctl restart sshd

echo "=== DONE ==="
echo "IMPORTANT:"
echo "✔ Root login allowed ONLY with SSH key"
echo "✔ Password login completely disabled"
echo
echo "Test in NEW terminal:"
echo "ssh root@SERVER_IP"
