#!/bin/bash
set -e

echo "=== Enabling SSH key login for root ==="

# Public key
PUBKEY='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqYatmrBBuQLQkleRtZDGi7ECc34LcLYK2AavX9tohmuILqIYYRRSrc5StqzSWkFe3S9Ke99lbqKu7a0GLsxsJe5rbsgxiZ8TLGoKmQhNlw3HxkbAif0R3t+dmfLn8ch2zhz14BJmb/YMmxH8LTTwW9MXz+YniPBXmG0IA0bT6Zrex2Bq9hx9vYytMuye+QIEx2SITKOU9r2QxUQ+CfLIimCNzsmXSwj3N7vEI3f9+StKaG//ZM0NAXL65dRQCkUrL+Z9AX8C2JlpLpVLgFcFDGkeckZ7FpceDrazoyu/UnHUKlvrWqAySh/gFZVmneIrQBQL2oAO0ZmrIuGHPfBOd Generated by ArvanCloud'

# Ensure .ssh exists
mkdir -p /root/.ssh
chmod 700 /root/.ssh

# Add public key
if ! grep -q "$PUBKEY" /root/.ssh/authorized_keys 2>/dev/null; then
  echo "$PUBKEY" >> /root/.ssh/authorized_keys
fi

chmod 600 /root/.ssh/authorized_keys
chown -R root:root /root/.ssh

echo "✔ Public key added to /root/.ssh/authorized_keys"

# Backup sshd_config
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak.$(date +%F_%T)

# Configure SSH
sed -i 's/^#\?PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config
sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
sed -i 's/^#\?ChallengeResponseAuthentication.*/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config
sed -i 's/^#\?KbdInteractiveAuthentication.*/KbdInteractiveAuthentication no/' /etc/ssh/sshd_config
sed -i 's/^#\?UsePAM.*/UsePAM no/' /etc/ssh/sshd_config
sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config

# Restart SSH
systemctl restart ssh || systemctl restart sshd

echo "✔ SSH restarted"
echo "=== DONE ==="
echo "Now test login in a NEW terminal:"
echo "ssh root@SERVER_IP"
